export const techStoreProducts = [
  {
    name: 'MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-One',
    picture:
      'https://m.media-amazon.com/images/I/71pwpiufqWL._AC_UF894,1000_QL80_.jpg',
    discount: true,
    originalPrice: 499,
    discountPrice: 450,
    reviewsCount: 10,
    reviewAverage: 2.5,
    available: true,
  },
  {
    name: 'Apple MacBook Air (2021)',
    picture:
      'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-space-gray-select-201810?wid=904&hei=840&fmt=jpeg&qlt=90&.v=1664472289661',
    discount: false,
    originalPrice: 999,
    discountPrice: null,
    reviewsCount: 25,
    reviewAverage: 4.8,
    available: true,
  },
  {
    name: 'Samsung Galaxy S21 Ultra 5G',
    picture: 'https://i.zst.com.br/thumbs/12/c/2f/-940175893.jpg',
    discount: true,
    originalPrice: 1299,
    discountPrice: 1199,
    reviewsCount: 30,
    reviewAverage: 4.6,
    available: true,
  },
  {
    name: 'Logitech MX Master 3 Wireless Mouse',
    picture: 'https://m.media-amazon.com/images/I/613a-3jtieL.jpg',
    discount: false,
    originalPrice: 99,
    discountPrice: null,
    reviewsCount: 15,
    reviewAverage: 3.9,
    available: false,
  },
  {
    name: 'Sony PlayStation 5',
    picture:
      'https://cdn.shoppub.io/cdn-cgi/image/w=1000,h=1000,q=80,f=auto/oficinadosbits/media/uploads/produtos/foto/dxzeirdf/file.png',
    discount: true,
    originalPrice: 499,
    discountPrice: 449,
    reviewsCount: 50,
    reviewAverage: 4.7,
    available: true,
  },
  {
    name: 'Bose QuietComfort 35 II Wireless Headphones',
    picture:
      'https://br.octoshop.com/media/catalog/product/cache/f392dc84e34552521f3f08ff16a74ad7/2/3/230-1_1.jpg',
    discount: false,
    originalPrice: 299,
    discountPrice: null,
    reviewsCount: 20,
    reviewAverage: 4.5,
    available: true,
  },
  {
    name: 'Dell XPS 13 9300 Laptop',
    picture:
      'https://m.media-amazon.com/images/I/613fdtVtglL.jpg',
    discount: true,
    originalPrice: 1199,
    discountPrice: 1099,
    reviewsCount: 12,
    reviewAverage: 4.4,
    available: true,
  },
  {
    name: 'Samsung 32-Inch 4K UHD Smart TV',
    picture:
      'https://image-us.samsung.com/SamsungUS/home/televisions-and-home-theater/tvs/qled-tvs/pdp/q50_2019/gallery/01_Q50_Front_Charcoal_Black.jpg?$product-details-jpg$',
    discount: true,
    originalPrice: 399,
    discountPrice: 349,
    reviewsCount: 40,
    reviewAverage: 4.6,
    available: false,
  },
  {
    name: 'Logitech G Pro X Mechanical Gaming Keyboard',
    picture:
      'https://images7.kabum.com.br/produtos/fotos/108087/teclado-mecanico-gamer-logitech-g-pro-com-layout-us-rgb-lightsync-design-tkl-cabo-destacavel-switch-gx-blue-clicky-920-009388_1644502490_g.jpg',
    discount: false,
    originalPrice: 149,
    discountPrice: null,
    reviewsCount: 18,
    reviewAverage: 4.8,
    available: true,
  },
  {
    name: 'Sony DualSense Edge Wireless Controller',
    picture:
      'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/HPNG2_AV1?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1665002953875',
    discount: false,
    originalPrice: 599,
    discountPrice: null,
    reviewsCount: 15,
    reviewAverage: 4.7,
    available: true,
  },
];
